// Numeric parity test for src/scenebot/quat_utils.js vs scipy.spatial.transform.Rotation.
// Fixtures generated by quat_fixtures.json.gen.py.

import { describe, it, expect } from "vitest";
import {
  wxyzToXyzw, xyzwToWxyz,
  multQuat, invQuat, applyQuat,
  quatFromYaw, headingFromQuatWxyz, headingFromQuatXyzw,
  quatAsMatrix,
  computeSe2AlignRoot, applySe2ToBody,
} from "../src/scenebot/quat_utils.js";
import fixtures from "./quat_fixtures.json" with { type: "json" };

const TOL = 1e-6;

function close(a, b, tol = TOL) {
  if (Array.isArray(a) || ArrayBuffer.isView(a)) {
    expect(a.length).toBe(b.length);
    for (let i = 0; i < a.length; i++) {
      expect(Math.abs(a[i] - b[i])).toBeLessThan(tol);
    }
  } else {
    expect(Math.abs(a - b)).toBeLessThan(tol);
  }
}

describe("wxyz <-> xyzw round-trip", () => {
  for (let i = 0; i < fixtures.random.length; i++) {
    it(`case ${i}`, () => {
      const c = fixtures.random[i];
      close(wxyzToXyzw(c.qWxyz), c.qXyzw);
      close(xyzwToWxyz(c.qXyzw), c.qWxyz);
    });
  }
});

describe("applyQuat (vs scipy Rotation.from_quat(q).apply(v))", () => {
  for (let i = 0; i < fixtures.random.length; i++) {
    it(`case ${i}`, () => {
      const c = fixtures.random[i];
      close(applyQuat(c.qXyzw, c.vec), c.rotated);
    });
  }
});

describe("multQuat (vs Rotation * Rotation)", () => {
  for (let i = 0; i < fixtures.random.length; i++) {
    it(`case ${i}`, () => {
      const c = fixtures.random[i];
      close(multQuat(c.qXyzw, c.qB), c.qProdXyzw);
    });
  }
});

describe("invQuat (vs Rotation.inv())", () => {
  for (let i = 0; i < fixtures.random.length; i++) {
    it(`case ${i}`, () => {
      const c = fixtures.random[i];
      // Note: scipy normalizes inv() to whatever sign convention; we only check
      // that q * q^-1 = identity (and matches scipy up to overall sign).
      const r = invQuat(c.qXyzw);
      // Compare rotation effect on a probe vector — sign-invariant.
      const probe = [1, 2, 3];
      close(applyQuat(r, probe), applyQuat(c.qInvXyzw, probe));
    });
  }
});

describe("headingFromQuatWxyz / Xyzw", () => {
  for (let i = 0; i < fixtures.random.length; i++) {
    it(`case ${i}`, () => {
      const c = fixtures.random[i];
      close(headingFromQuatWxyz(c.qWxyz), c.yawWxyz);
      close(headingFromQuatXyzw(c.qXyzw), c.yawWxyz);
    });
  }
});

describe("quatFromYaw (vs Rotation.from_euler('z', a))", () => {
  for (const c of fixtures.yaw) {
    it(`angle=${c.angle.toFixed(3)}`, () => {
      close(quatFromYaw(c.angle), c.qXyzw);
    });
  }
});

describe("quatAsMatrix (vs Rotation.as_matrix())", () => {
  for (let i = 0; i < fixtures.random.length; i++) {
    it(`case ${i}`, () => {
      const c = fixtures.random[i];
      close(Array.from(quatAsMatrix(c.qXyzw)), c.matRowMajor);
    });
  }
});

describe("computeSe2AlignRoot (vs stitch_core.compute_se2_align_root)", () => {
  for (let i = 0; i < fixtures.se2.length; i++) {
    it(`case ${i}`, () => {
      const c = fixtures.se2[i];
      const { rDelta, t } = computeSe2AlignRoot(
        c.anchorPosFrom, c.anchorQuatFromWxyz, c.anchorPosTo, c.anchorQuatToWxyz,
      );
      // Compare rotation effect (sign-invariant) and translation directly.
      const probe = [1, 2, 3];
      close(applyQuat(rDelta, probe), applyQuat(c.rDeltaXyzw, probe));
      close(Array.from(t), c.t);
    });
  }
});

describe("applySe2ToBody (vs apply_se2_rigid_to_bodies)", () => {
  for (let i = 0; i < fixtures.se2.length; i++) {
    it(`case ${i}`, () => {
      const c = fixtures.se2[i];
      const posOut = new Float64Array(3);
      const quatOut = new Float64Array(4);
      applySe2ToBody(c.rDeltaXyzw, c.t, c.probePos, c.probeQuatWxyz, posOut, quatOut);
      close(Array.from(posOut), c.outPos);
      // quat sign-invariant check via rotation effect
      const probe = [1, 2, 3];
      const xyzwOut = wxyzToXyzw(quatOut);
      const xyzwRef = wxyzToXyzw(c.outQuatWxyz);
      close(applyQuat(xyzwOut, probe), applyQuat(xyzwRef, probe));
    });
  }
});
